### ISSUE TITLE
Vote for HTML Style Guide

### ISSUE THREAD

**Issue by Kristories** [Kristories/awesome-guidelines#24]
#20 [HTML Style Guide](https://marcobiedermann.github.io/html-style-guide/)

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN96NC08TZM3TCACJ08T3123/%2B1)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN96NC08TZM3TCACJ08T3123/%2B1/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN96NC08TZM3TCACJ08T3123/-1)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BN96NC08TZM3TCACJ08T3123/-1/vote)

**Comment by yordis** [comment]
I clicl on the voting without knowing 🤣
